"""_extract_tool_calls must parse Qwen, Llama, Mistral, and DeepSeek tool-call
formats.

Regression test for a bug where the parser only recognised Qwen's
<tool_call> tag and silently dropped tool calls from other model families.
"""

import json

from agenttune.agentic.rollout_engines.rollout_factory import (
    _extract_tool_calls,
    coerce_tool_call_arguments_to_dict,
    fold_tool_messages_into_user,
)

# Fullwidth "｜"/"▁" characters, not ASCII "|"/"_" — this is the literal
# string deepseek-ai/DeepSeek-V3's own tokenizer renders via
# apply_chat_template for a single-tool-call assistant turn, not a guess.
_DEEPSEEK_SAMPLE = (
    "<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>function<｜tool▁sep｜>get_weather\n"
    '```json\n{"city": "Paris"}\n```<｜tool▁call▁end｜>'
)


def test_qwen_tool_call_tag():
    text = '<tool_call>{"name": "get_weather", "arguments": {"city": "Paris"}}</tool_call>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"city": "Paris"}'},
        }
    ]


def test_llama_function_tag():
    text = '<function=get_weather>{"city": "Paris"}</function>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"city": "Paris"}'},
        }
    ]


def test_mistral_tool_calls_marker():
    text = '[TOOL_CALLS] [{"name": "get_weather", "arguments": {"city": "Paris"}}]'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"city": "Paris"}'},
        }
    ]


def test_mistral_bracket_name_format():
    # Real string generated by mistralai/Ministral-3-3B-Instruct-2512-BF16.
    # Its AutoTokenizer auto-selects the "mistral_common" backend, which
    # renders tool calls as "[TOOL_CALLS]NAME[ARGS]{json}" -- confirmed
    # against mistral_common's own tokenizer source
    # (_encode_tool_calls_in_assistant_message), not guessed. This is a
    # different, newer format than the "[TOOL_CALLS] [...]" one above,
    # which its own chat_template.jinja (not actually used at generation
    # time) still describes.
    text = '[TOOL_CALLS]get_weather[ARGS]{"location": "Tokyo"}'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_mistral_bracket_name_nested_arguments():
    text = '[TOOL_CALLS]get_weather[ARGS]{"location": {"city": "Tokyo", "country": "JP"}}'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result[0]["function"]["arguments"] == '{"location": {"city": "Tokyo", "country": "JP"}}'


def test_mistral_bracket_name_multiple_calls():
    text = (
        '[TOOL_CALLS]get_weather[ARGS]{"location": "Tokyo"}[TOOL_CALLS]get_time[ARGS]{"tz": "JST"}'
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert [c["function"]["name"] for c in result] == ["get_weather", "get_time"]


def test_mistral_tool_calls_marker_still_wins_over_bracket_fallback():
    # Regression guard: the older [TOOL_CALLS] [...] format must not fall
    # through to the newer bracket-name parser.
    text = '[TOOL_CALLS] [{"name": "get_weather", "arguments": {"city": "Paris"}}]'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result[0]["function"]["arguments"] == '{"city": "Paris"}'


def test_mistral_plain_bracket_greedy_format():
    # Real string generated by mistralai/Ministral-3-3B-Instruct-2512-BF16
    # under GREEDY decoding (do_sample=False) -- a second, different, also
    # reproducible surface form from the same model/tokenizer: plain
    # bracket characters around the name, no "[TOOL_CALLS]"/"[ARGS]"
    # special tokens at all (those only appear under sampling).
    text = ' [get_weather]{"location": "Tokyo"}</s>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_mistral_bracket_name_still_wins_over_plain_bracket_fallback():
    # Regression guard: the sampling-mode "[TOOL_CALLS]NAME[ARGS]{json}"
    # format must never fall through to the plain-bracket parser, which
    # would otherwise match "[ARGS]" itself as if it were the function
    # name (this was a real bug -- see the module docstring above
    # _MISTRAL_PLAIN_BRACKET_NAME_RE).
    text = '[TOOL_CALLS]get_weather[ARGS]{"location": "Tokyo"}'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result[0]["function"]["name"] == "get_weather"


def test_plain_text_returns_none():
    text = "The weather in Paris is sunny."
    assert _extract_tool_calls({"role": "assistant", "content": text}, text) is None


def test_llama_malformed_arguments_returns_none():
    text = "<function=broken>{not json}</function>"
    assert _extract_tool_calls({"role": "assistant", "content": text}, text) is None


def test_llama_multiple_calls():
    text = (
        '<function=get_weather>{"city": "Paris"}</function>'
        '<function=get_time>{"tz": "CET"}</function>'
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert [c["function"]["name"] for c in result] == ["get_weather", "get_time"]


def test_llama_builtin_python_tag_json_format():
    # Real string rendered by meta-llama/Llama-3.2-1B-Instruct's own
    # tokenizer.apply_chat_template(tools=[...]) for a single-tool-call
    # assistant turn. This is Llama's *built-in* JSON tool format, distinct
    # from the <function=NAME>{...}</function> custom-tool format above --
    # "function" here is the name itself (a string), and args live under
    # "parameters", not "arguments". Regression test: this used to raise
    # AttributeError in _normalise_tool_calls, which assumed "function" was
    # always a nested {name, arguments} dict.
    text = (
        '<|python_tag|>{"type": "function", "function": "get_weather", '
        '"parameters": {"location": "Tokyo"}}<|eom_id|>'
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_llama_nested_json_arguments():
    text = '<function=get_weather>{"location": {"city": "Paris", "country": "FR"}}</function>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result[0]["function"]["arguments"] == '{"location": {"city": "Paris", "country": "FR"}}'


def test_qwen35_function_parameter_tags():
    # Real string generated by Qwen/Qwen3.5-4B's own tokenizer chat
    # template for a single-tool-call assistant turn. A completely
    # different surface form from Qwen3's plain
    # "<tool_call>{json}</tool_call>": each argument is its own
    # "<parameter=NAME>value</parameter>" tag inside a Llama-style
    # "<function=NAME>...</function>" block. Regression test for a
    # real-model finding: the parser didn't recognise this at all
    # (returned None) until this format was added.
    text = (
        "<tool_call>\n"
        "<function=get_weather>\n"
        "<parameter=location>\n"
        "Tokyo\n"
        "</parameter>\n"
        "</function>\n"
        "</tool_call>"
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_qwen35_multiple_parameters():
    text = (
        "<tool_call>\n"
        "<function=get_weather>\n"
        "<parameter=location>\n"
        "Tokyo\n"
        "</parameter>\n"
        "<parameter=units>\n"
        "celsius\n"
        "</parameter>\n"
        "</function>\n"
        "</tool_call>"
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    args = json.loads(result[0]["function"]["arguments"])
    assert args == {"location": "Tokyo", "units": "celsius"}


def test_gemma4_tool_call():
    # Real string generated by google/gemma-4-E2B-it's own tokenizer chat
    # template. A third, unrelated tool-call syntax under the "Gemma"
    # name: Gemma 3 has no tool-calling template at all; Gemma 4 has one,
    # but it's a custom minified-object format, not JSON and not XML tags
    # -- note the ASYMMETRIC delimiters ("<|tool_call>" opens, "<tool_call|>"
    # closes) and the custom string-quote marker ("<|\"|>...<|\"|>"
    # instead of `"`).
    text = '<|tool_call>call:get_weather{location:<|"|>Tokyo<|"|>}<tool_call|><|tool_response>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_gemma4_multiple_arguments():
    text = (
        '<|tool_call>call:get_weather{location:<|"|>Tokyo<|"|>,units:<|"|>celsius<|"|>}<tool_call|>'
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    args = json.loads(result[0]["function"]["arguments"])
    assert args == {"location": "Tokyo", "units": "celsius"}


def test_deepseek_tool_call():
    result = _extract_tool_calls(
        {"role": "assistant", "content": _DEEPSEEK_SAMPLE}, _DEEPSEEK_SAMPLE
    )
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"city": "Paris"}'},
        }
    ]


def test_deepseek_multiple_calls():
    text = (
        "<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>function<｜tool▁sep｜>get_weather\n"
        '```json\n{"city": "Paris"}\n```<｜tool▁call▁end｜>\n'
        "<｜tool▁call▁begin｜>function<｜tool▁sep｜>get_time\n"
        '```json\n{"tz": "CET"}\n```<｜tool▁call▁end｜><｜tool▁calls▁end｜>'
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert [c["function"]["name"] for c in result] == ["get_weather", "get_time"]


def test_deepseek_malformed_arguments_returns_none():
    text = (
        "<｜tool▁call▁begin｜>function<｜tool▁sep｜>broken\n"
        "```json\n{not json}\n```<｜tool▁call▁end｜>"
    )
    assert _extract_tool_calls({"role": "assistant", "content": text}, text) is None


def test_glm_arg_key_value_tool_call():
    # Real string rendered by zai-org/GLM-4.5-Air's own tokenizer for a
    # single-tool-call assistant turn — GLM reuses Qwen's <tool_call> tag
    # but with arg_key/arg_value pairs instead of a JSON body.
    text = "<tool_call>get_weather\n<arg_key>city</arg_key>\n<arg_value>Paris</arg_value>\n</tool_call>"
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"city": "Paris"}'},
        }
    ]


def test_glm_no_newline_after_name():
    # Real string rendered by zai-org/GLM-4.7-Flash's own tokenizer for a
    # single-tool-call assistant turn. Unlike GLM-4.5-Air (see above), the
    # 4.7-Flash template puts no whitespace at all between the function
    # name and "<arg_key>" -- regression test for a format drift that made
    # the old (newline-requiring) regex silently drop every 4.7-Flash call.
    text = (
        "<tool_call>get_weather<arg_key>location</arg_key><arg_value>Tokyo</arg_value></tool_call>"
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_glm_multiple_calls():
    text = (
        "<tool_call>get_weather\n<arg_key>city</arg_key>\n<arg_value>Paris</arg_value>\n</tool_call>"
        "<tool_call>get_time\n<arg_key>tz</arg_key>\n<arg_value>CET</arg_value>\n</tool_call>"
    )
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert [c["function"]["name"] for c in result] == ["get_weather", "get_time"]


def test_qwen_json_tag_still_wins_over_glm_fallback():
    # Regression guard: a plain Qwen JSON <tool_call> must never fall
    # through to the GLM arg_key/arg_value parser.
    text = '<tool_call>{"name": "get_weather", "arguments": {"city": "Paris"}}</tool_call>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result[0]["function"]["arguments"] == '{"city": "Paris"}'


def test_functionary_tool_call():
    # Real string rendered by meetkai/functionary-small-v3.2's own
    # tokenizer for a single-tool-call assistant turn.
    text = '>>>get_weather\n{"city": "Paris"}'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"city": "Paris"}'},
        }
    ]


def test_functionary_all_prefix_is_not_a_tool_call():
    text = ">>>all\nThe weather in Paris is sunny."
    assert _extract_tool_calls({"role": "assistant", "content": text}, text) is None


def test_functionary_multiple_calls():
    text = '>>>get_weather\n{"city": "Paris"}>>>get_time\n{"tz": "CET"}'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert [c["function"]["name"] for c in result] == ["get_weather", "get_time"]


def test_functionary_trailing_special_token_after_json():
    # Real output generated by meetkai/functionary-small-v3.2: a trailing
    # special token (rendered as literal text, e.g. "<|eot_id|>") right
    # after the closing "}" used to make the old regex's lookahead
    # (require "\n>>>" or end-of-string immediately after the JSON) fail,
    # silently dropping every real generated call.
    text = '>>>get_weather\n{"location": "Tokyo"}<|eot_id|>'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result == [
        {
            "type": "function",
            "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
        }
    ]


def test_functionary_nested_arguments():
    text = '>>>get_weather\n{"location": {"city": "Tokyo", "country": "JP"}}'
    result = _extract_tool_calls({"role": "assistant", "content": text}, text)
    assert result[0]["function"]["arguments"] == '{"location": {"city": "Tokyo", "country": "JP"}}'


def test_fold_tool_messages_into_user_single_call():
    # Regression test: chat templates with no "tool" role at all (e.g.
    # Gemma's) hard-fail ("Conversation roles must alternate...") on one.
    # Folding it into a plain "user" turn keeps strict alternation intact.
    conversation = [
        {"role": "user", "content": "What's the weather in Tokyo?"},
        {
            "role": "assistant",
            "content": '{"name": "get_weather", "arguments": {"location": "Tokyo"}}',
        },
        {"role": "tool", "name": "get_weather", "content": "19.6C", "tool_call_id": "call_1"},
    ]
    folded = fold_tool_messages_into_user(conversation)
    assert [m["role"] for m in folded] == ["user", "assistant", "user"]
    assert "19.6C" in folded[2]["content"]


def test_fold_tool_messages_into_user_merges_consecutive_calls():
    # Two tool results from parallel tool calls must merge into ONE user
    # turn -- two consecutive "user" turns would break alternation just as
    # badly as a "tool" role does.
    conversation = [
        {"role": "user", "content": "q"},
        {"role": "assistant", "content": "..."},
        {"role": "tool", "name": "a", "content": "result_a"},
        {"role": "tool", "name": "b", "content": "result_b"},
    ]
    folded = fold_tool_messages_into_user(conversation)
    assert [m["role"] for m in folded] == ["user", "assistant", "user"]
    assert "result_a" in folded[2]["content"]
    assert "result_b" in folded[2]["content"]


def test_fold_tool_messages_into_user_leaves_others_unchanged():
    conversation = [
        {"role": "system", "content": "s"},
        {"role": "user", "content": "q"},
        {"role": "assistant", "content": "a"},
    ]
    assert fold_tool_messages_into_user(conversation) == conversation


def test_coerce_tool_call_arguments_to_dict():
    # Regression test: Qwen3.5's real chat template requires
    # tool_calls[].function.arguments to be a dict when re-encoding
    # history, and raises a plain TypeError ("Can only get item pairs
    # from a mapping") from inside its own template on the JSON string
    # every other convention here uses.
    conversation = [
        {"role": "user", "content": "q"},
        {
            "role": "assistant",
            "content": None,
            "tool_calls": [
                {
                    "type": "function",
                    "function": {"name": "get_weather", "arguments": '{"location": "Tokyo"}'},
                }
            ],
        },
    ]
    coerced = coerce_tool_call_arguments_to_dict(conversation)
    assert coerced[1]["tool_calls"][0]["function"]["arguments"] == {"location": "Tokyo"}
    # original untouched
    assert conversation[1]["tool_calls"][0]["function"]["arguments"] == '{"location": "Tokyo"}'


def test_coerce_tool_call_arguments_to_dict_leaves_others_unchanged():
    conversation = [
        {"role": "system", "content": "s"},
        {"role": "user", "content": "q"},
        {"role": "assistant", "content": "a"},
    ]
    assert coerce_tool_call_arguments_to_dict(conversation) == conversation


if __name__ == "__main__":
    test_qwen_tool_call_tag()
    test_llama_function_tag()
    test_mistral_tool_calls_marker()
    test_mistral_bracket_name_format()
    test_mistral_bracket_name_nested_arguments()
    test_mistral_bracket_name_multiple_calls()
    test_mistral_tool_calls_marker_still_wins_over_bracket_fallback()
    test_mistral_plain_bracket_greedy_format()
    test_mistral_bracket_name_still_wins_over_plain_bracket_fallback()
    test_plain_text_returns_none()
    test_llama_malformed_arguments_returns_none()
    test_llama_builtin_python_tag_json_format()
    test_llama_multiple_calls()
    test_llama_nested_json_arguments()
    test_qwen35_function_parameter_tags()
    test_qwen35_multiple_parameters()
    test_gemma4_tool_call()
    test_gemma4_multiple_arguments()
    test_deepseek_tool_call()
    test_deepseek_multiple_calls()
    test_deepseek_malformed_arguments_returns_none()
    test_glm_arg_key_value_tool_call()
    test_glm_no_newline_after_name()
    test_glm_multiple_calls()
    test_qwen_json_tag_still_wins_over_glm_fallback()
    test_functionary_tool_call()
    test_functionary_all_prefix_is_not_a_tool_call()
    test_functionary_multiple_calls()
    test_functionary_trailing_special_token_after_json()
    test_functionary_nested_arguments()
    test_fold_tool_messages_into_user_single_call()
    test_fold_tool_messages_into_user_merges_consecutive_calls()
    test_fold_tool_messages_into_user_leaves_others_unchanged()
    test_coerce_tool_call_arguments_to_dict()
    test_coerce_tool_call_arguments_to_dict_leaves_others_unchanged()
    print("ok")
